USE [dataWarehouse]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE [Fact].[ContractTotals](
	[FCT_ID] [int] IDENTITY(1,1) NOT NULL,
	[DCnct_ID] [int] NOT NULL,
	[ContractName] [varchar](50) NOT NULL,
	[BilledAmt] decimal(10,2) NOT NULL,
	[CostAmt] decimal(10,2) NOT NULL,
	[RM_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Fact].[ContractTotals]  WITH CHECK ADD FOREIGN KEY([DCnct_ID])
REFERENCES [Dim].[Contract] ([DCnct_ID])
GO

ALTER TABLE [Fact].[ContractTotals]  WITH CHECK ADD FOREIGN KEY([RM_ID])
REFERENCES [Dim].[ReportMth] ([RM_ID])
GO